from werkzeug.exceptions import NotFound


def audit():
    raise NotFound
